version: 2.4
#   _    _ _ _   _                 _                        _   _ _           _
#  | |  | | | | (_)               | |           /\         | | (_) |         | |
#  | |  | | | |_ _ _ __ ___   __ _| |_ ___     /  \   _ __ | |_ _| |__   ___ | |_
#  | |  | | | __| | '_ ` _ \ / _` | __/ _ \   / /\ \ | '_ \| __| | '_ \ / _ \| __|
#  | |__| | | |_| | | | | | | (_| | ||  __/  / ____ \| | | | |_| | |_) | (_) | |_
#  \____/|_|\__|_|_| |_| |_|\__,_|\__\___| /_/    \_\_| |_|\__|_|_.__/ \___/ \__|

debug: false
#Antibotmode has the utility of mitigating the attack, blacklisting + ip possible,
#I tried to make it as secure as possible so as to blacklist only malicious connections
#
#At the end of the attack the blacklist is cleared for safety
#in the future I will try to make the checks as safe as possible
antibotmode:
  #Duration of the anti-botmode when activated
  keep: 15
  #If there are 5 connections in 1 second the antibot mode will be activated!
  trigger: 5

#safemode, on the other hand, has the task of making access possible
#through a ping system, and refreshing the server list

safemode:
  #When 75% of the IPs have been blacklisted, safemode is activated
  percent: 75
  #Checks Per Second for enable while antibotmode is online
  modifier: 100
  #duration of safemode when activated
  keep: 20

#Pingmode allows player connections to your server!
pingmode:
  #Duration of the ping-mode when activated
  keep: 10
  #How many pings in 1 second does it take to activate the protection?
  trigger: 100
  #MotdKiller Protection
  #Send the server logo during a ping attack?
  send_info: false

#Minimum online time to be whitelisted
playtime_for_whitelist: 2 #minutes

taskmanager:
  analyzer: 5 #seconds
  clearcache: 2 #minutes
  queue: 1 #minutes

#This is the section where you can change the check settings
#How does it work?
#
#There is an analyzer, The analyzer is reset every 5 seconds during
#anti-botmode or safe mode, If an ip reaches the maximum number of values
#before resetting the analyzer, It is blacklisted
#
#Don't touch anything if you don't know what you are doing!
blacklist:
  #This is the section where you can change the
  #maximum number to get the blacklist for an IP
  max: 50
  #If during the safe mode a bot enters and disconnects immediately adds 20
  bypass: 20
  #If the antibot mode is online every time the bot tries to connect it adds 15
  antibot_mode: 15
  #How much the queue clears up if the antibotmode is online adds 15
  queue: 15
  #on ping during antibotmode
  ping: 3
  #if percent < 50% add 5 on connection
  usain: 5
  #Increaser Only used with ping attacks!
  ping_mode: 5
  #strange situation
  strange: 26

checks:
  #slowmode check
  slowmode:
    #When a user logs in for the first time and is logged
    #out and does not come back in 15 seconds he will be
    #blacklisted for 2 to 6 minutes
    duration: 15 #seconds
    #Do I have to disconnect players within 30 seconds
    #of entering the server when it is attacked?
    disconnect: true
    #enable this check?
    enable: true
  timer:
    #The timer check is an advanced check,
    #from a long disconnect screen a message
    #eg: "reconnect in 5 seconds"
    #if the player reconnects in those 5 seconds
    #he is whitelisted
    #here you can set minium time
    min: 5 #seconds
    #here you can set max time
    max: 10 #seconds
    #When the time for verification runs out,
    #you have 1 second to enter
    between: 1000 #milliseconds (1 SECOND)
    #If you reconnect earlier (in the case of
    #a standard configuration) after 2 failed
    #checks it will be blacklisted
    increaser: 25
    #There must be exactly 3 correct
    #checks to be whitelisted
    repeat: 1
    #If you don't enable it
    #you are a really bad person :c
    enable: true
filter: #works on Waterfall Spigot & PaperSpigot no on BungeeCord
  - 'InitialHandler has'
  - 'Connection reset by peer'
  - 'Unexpected packet received'
  - 'read timed out'
  - 'to process!'
  - 'Empty Packet!'
  - 'bad packet ID'
  - 'InitialHandler - encountered exception'
  - 'com.mojang.authlib'
  - 'lost connection: Timed out'
  - 'lost connection: Disconnected'
  - 'Took too long to log in'
  - 'Another plugin has cancelled the connection for' # for luckyperms on spigot