version: 2.9
#   _    _ _ _   _                 _                        _   _ _           _
#  | |  | | | | (_)               | |           /\         | | (_) |         | |
#  | |  | | | |_ _ _ __ ___   __ _| |_ ___     /  \   _ __ | |_ _| |__   ___ | |_
#  | |  | | | __| | '_ ` _ \ / _` | __/ _ \   / /\ \ | '_ \| __| | '_ \ / _ \| __|
#  | |__| | | |_| | | | | | | (_| | ||  __/  / ____ \| | | | |_| | |_) | (_) | |_
#  \____/|_|\__|_|_| |_| |_|\__,_|\__\___| /_/    \_\_| |_|\__|_|_.__/ \___/ \__|

debug: false
#Antibotmode has the utility of mitigating the attack, blacklisting + ip possible,
#I tried to make it as secure as possible so as to blacklist only malicious connections
#
#At the end of the attack the blacklist is cleared for safety
#in the future I will try to make the checks as safe as possible
antibotmode:
  #Duration of the anti-botmode when activated
  keep: 15
  #If there are 5 connections in 1 second the antibot mode will be activated!
  trigger: 5

#safemode, on the other hand, has the task of making access possible
#through the timer check

safemode:
  #When 95% of the IPs have been blacklisted, safemode is activated
  percent: 95
  #Checks Per Second for enable while antibotmode is online
  modifier: 100
  #duration of safemode when activated
  keep: 20

#Pingmode allows player connections to your server!
pingmode:
  #Duration of the ping-mode when activated
  keep: 10
  #How many pings in 1 second does it take to activate the protection?
  trigger: 100
  #MotdKiller Protection
  #Send the server logo during a ping attack?
  send_info: true

#Works Only on Bungeecord Waterfall ect...
handshakemode:
  #Duration of handshakemode
  keep: 10
  #How many handshake in 1 second to enable?
  trigger: 150 #Set (Your online players * 4) | If you have 40 average online players you have to do 40 x 3 and the result will be the value to write
  #if the handshake has an invalid protocol do I have to blacklist it?
  blacklist_protocol: true
  #Enable this mode?
  enabled: true

#Minimum online time to be whitelisted
playtime_for_whitelist: 2 #minutes

taskmanager:
  clearcache: 5 #minutes
  queue: 1 #minutes
  account: 60 #seconnds

checks:
  #first join check
  first_join:
    enabled: true
  #slowmode check
  slowmode:
    #When a user logs in for the first time and is logged
    #out and does not come back in 15 seconds he will be
    #blacklisted for 2 to 6 minutes
    duration: 15 #seconds
    #Do I have to disconnect players within 30 seconds
    #of entering the server when it is attacked?
    disconnect: true
    #Maximum accounts for each ip
    #connected at same time
    limit: 4
    #If a player is kicked out for having too many online accounts,
    #do I have to blacklist him?
    blacklist_on_limit: true
    #Enabble this check?
    enable: true
  account:
    #This check checks the number of accounts entered by the same ip within
    #60 (can be changed in the taskmanager) seconds during antibotmode
    #
    #Number of accounts to be blacklisted
    limit: 3
    #Enable this check
    enable: true
  timer:
    #The timer check is an advanced check,
    #from a long disconnect screen a message
    #eg: "reconnect in 5 seconds"
    #if the player reconnects in those 5 seconds
    #he is whitelisted
    #here you can set minium time
    min: 5 #seconds
    #here you can set max time
    max: 10 #seconds
    #When the time for verification runs out,
    #you have 1 second to enter
    between: 1000 #milliseconds (1 SECOND)
    #There must be exactly 3 correct
    #checks to be whitelisted
    repeat: 3
    #If you don't enable it
    #you are a really bad person :c
    enable: true
filter: #works on Waterfall Spigot & PaperSpigot no on BungeeCord
  - 'InitialHandler has'
  - 'Connection reset by peer'
  - 'Unexpected packet received'
  - 'read timed out'
  - 'to process!'
  - 'Empty Packet!'
  - 'corrupted'
  - 'has pinged'
  - 'has connected'
  - 'bad packet ID'
  - 'InitialHandler - encountered exception'
  - 'com.mojang.authlib'
  - 'lost connection: Timed out'
  - 'lost connection: Disconnected'
  - 'Took too long to log in'
  - 'Another plugin has cancelled the connection for' # for luckyperms on spigot
  - 'disconnected with' #for slowjoincheck