name: UltimateAntiBot
version: ${project.version}
main: me.kr1s_d.ultimateantibot.spigot.UltimateAntibotSpigot
api-version: 1.13
authors: [Kr1S_D]
description: Best AntiBot System
commands:
  ultimateantibot:
    description: Main commands
    aliases: [uab]